//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
namespace form_1a.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class form_1C
    {
        public int Id { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:MM-dd-yyyy}")]
        public Nullable<System.DateTime> entry { get; set; }
        public string year { get; set; }
        public string month_year1 { get; set; }
        public string month_year2 { get; set; }
        public string reason { get; set; }
        [Required(ErrorMessage = "Name is required.")]
        public string name_of_person { get; set; }
        [Required(ErrorMessage = "Date of birth is required.")]
        public Nullable<System.DateTime> date_of_birth { get; set; }
        public string father_name { get; set; }
        [Required(ErrorMessage = "Name of mother is required.")]
        public string mother_name { get; set; }
        public string issued_name { get; set; }
        public string officer_name { get; set; }
        public string officer_title { get; set; }
        public string verifier_name { get; set; }
        public string verifier_title { get; set; }
        public string payment { get; set; }
        public string or_no { get; set; }
        [Required(ErrorMessage = "Date of birth is required.")]
        public Nullable<System.DateTime> date_paid { get; set; }
        public string filename { get; set; }
    }
}
