//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace form_1a.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form_3A
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> entry { get; set; }
        public string page { get; set; }
        public string book { get; set; }
        public string husband_name { get; set; }
        public string wife_name { get; set; }
        public string husband_age { get; set; }
        public string wife_age { get; set; }
        public string husband_citizenship { get; set; }
        public string wife_citizenship { get; set; }
        public string husband_civil_status { get; set; }
        public string wife_civil_status { get; set; }
        public string husband_father { get; set; }
        public string wife_father { get; set; }
        public string husband_mother { get; set; }
        public string wife_mother { get; set; }
        public string reg_no { get; set; }
        public Nullable<System.DateTime> date_of_reg { get; set; }
        public Nullable<System.DateTime> date_of_marriage { get; set; }
        public string place_of_marriage { get; set; }
        public string issued_to { get; set; }
        public string officer_name { get; set; }
        public string officer_title { get; set; }
        public string verifier_name { get; set; }
        public string verifier_title { get; set; }
        public string payment { get; set; }
        public string or_no { get; set; }
        public Nullable<System.DateTime> date_paid { get; set; }
    }
}
