//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
namespace form_1a.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class form_2B
    {
        public int Id { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:MM-dd-yyyy}")]
        public Nullable<System.DateTime> entry { get; set; }
        [Required(ErrorMessage = "Name is required.")]
        public string name { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:MM-dd-yyyy}")]
        [Required(ErrorMessage = "Date of death is required.")]
        public Nullable<System.DateTime> date_of_death { get; set; }
        public string year { get; set; }
        public string issued_name { get; set; }
        public string officer_name { get; set; }
        public string officer_title { get; set; }
        public string verifier_name { get; set; }
        public string verifier_title { get; set; }
        public string payment { get; set; }
        public string or_no { get; set; }
        [Required(ErrorMessage = "Date paid is required.")]
        public Nullable<System.DateTime> date_paid { get; set; }
        public string filename { get; set; }
    }
}
