//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace form_1a.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class form_3B
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> entry { get; set; }
        public string husband_name { get; set; }
        public string wife_name { get; set; }
        public Nullable<System.DateTime> date_of_marriage { get; set; }
        public string year { get; set; }
        public string issued_name { get; set; }
        public string officer_name { get; set; }
        public string officer_title { get; set; }
        public string verifier_name { get; set; }
        public string verifier_title { get; set; }
        public string payment { get; set; }
        public string or_no { get; set; }
        public Nullable<System.DateTime> date_paid { get; set; }
    }
}
