//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace form_1a.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form_1A
    {
        public int Id { get; set; }
        public string lcr_reg_no { get; set; }
        public Nullable<System.DateTime> date_of_reg { get; set; }
        public string name_child { get; set; }
        public string sex { get; set; }
        public Nullable<System.DateTime> date_of_birth { get; set; }
        public string place_of_birth { get; set; }
        public string name_of_mother { get; set; }
        public string citizenship_of_mother { get; set; }
        public string name_of_father { get; set; }
        public string citizenship_of_father { get; set; }
        public Nullable<System.DateTime> date_of_marriage_of_parents { get; set; }
        public string place_of_marriage_of_parents { get; set; }
        public string issued_to { get; set; }
        public string officer_name { get; set; }
        public string officer_title { get; set; }
        public string verifier_name { get; set; }
        public string verifier_title { get; set; }
        public string payment { get; set; }
        public string or_no { get; set; }
        public Nullable<System.DateTime> date_paid { get; set; }
        public string page { get; set; }
        public string book { get; set; }
        public Nullable<System.DateTime> entry { get; set; }
    }
}
