//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace form_1a.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Form_1AEntities1 : DbContext
    {
        public Form_1AEntities1()
            : base("name=Form_1AEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Form_1A> Form_1A { get; set; }
        public virtual DbSet<form_1C> form_1C { get; set; }
        public virtual DbSet<Form_2A> Form_2A { get; set; }
        public virtual DbSet<form_2B> form_2B { get; set; }
        public virtual DbSet<Form_3A> Form_3A { get; set; }
        public virtual DbSet<form_3B> form_3B { get; set; }
        public virtual DbSet<form_3C> form_3C { get; set; }
        public virtual DbSet<Form_1B> Form_1B { get; set; }
    }
}
